\
Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend\
Err?=(none)/Reinst-required\
Name\
\
accountsservice\
acpid\
adduser\
apache2\
apache2-bin\
apache2-data\
apache2-dev\
apache2-utils\
apparmor\
apport\
apport-symptoms\
apt\
apt-transport-https\
apt-utils\
apt-xapian-index\
aptitude\
aptitude-common\
at\
autotools-dev\
base-files\
base-passwd\
bash\
bash-completion\
bc\
bind9-host\
binutils\
bsdmainutils\
bsdutils\
build-essential\
bundler\
busybox-initramfs\
busybox-static\
byobu\
bzip2\
ca-certificates\
cloud-guest-utils\
cloud-init\
comerr-dev\
command-not-found\
command-not-found-data\
console-setup\
coreutils\
cpio\
cpp\
cpp-4.8\
cron\
cryptsetup\
cryptsetup-bin\
curl\
dash\
dbus\
debconf\
debconf-i18n\
debhelper\
debianutils\
dh-apparmor\
dh-python\
diffutils\
dmidecode\
dmsetup\
dnsutils\
dosfstools\
dpkg\
dpkg-dev\
e2fslibs:amd64\
e2fsprogs\
eatmydata\
ed\
eject\
ethtool\
fakeroot\
file\
findutils\
fontconfig\
fontconfig-config\
fonts-dejavu-core\
fonts-ubuntu-font-family-console\
friendly-recovery\
ftp\
fuse\
g++\
g++-4.8\
gawk\
gcc\
gcc-4.8\
gcc-4.8-base:amd64\
gcc-4.9-base:amd64\
gdisk\
geoip-database\
gettext\
gettext-base\
ghostscript\
gir1.2-freedesktop\
gir1.2-gdkpixbuf-2.0\
gir1.2-glib-2.0\
gir1.2-rsvg-2.0\
git\
git-man\
gnupg\
gpgv\
grep\
groff-base\
grub-common\
grub-gfxpayload-lists\
grub-legacy-ec2\
grub-pc\
grub-pc-bin\
grub2-common\
gsfonts\
gzip\
hdparm\
hicolor-icon-theme\
hostname\
ifupdown\
imagemagick\
imagemagick-common\
info\
init-system-helpers\
initramfs-tools\
initramfs-tools-bin\
initscripts\
insserv\
install-info\
intltool-debian\
iproute2\
iptables\
iputils-ping\
iputils-tracepath\
irqbalance\
isc-dhcp-client\
isc-dhcp-common\
iso-codes\
kbd\
keyboard-configuration\
klibc-utils\
kmod\
krb5-locales\
krb5-multidev\
landscape-client\
landscape-common\
language-selector-common\
laptop-detect\
less\
libaccountsservice0:amd64\
libacl1:amd64\
libalgorithm-diff-perl\
libalgorithm-diff-xs-perl\
libalgorithm-merge-perl\
libapache2-mod-passenger\
libapache2-mod-php5\
libapparmor-perl\
libapparmor1:amd64\
libapr1:amd64\
libapr1-dev\
libaprutil1:amd64\
libaprutil1-dbd-sqlite3:amd64\
libaprutil1-dev\
libaprutil1-ldap:amd64\
libapt-inst1.5:amd64\
libapt-pkg4.12:amd64\
libarchive-extract-perl\
libasan0:amd64\
libasn1-8-heimdal:amd64\
libasprintf-dev:amd64\
libasprintf0c2:amd64\
libatomic1:amd64\
libattr1:amd64\
libaudit-common\
libaudit1:amd64\
libavahi-client3:amd64\
libavahi-common-data:amd64\
libavahi-common3:amd64\
libbind9-90\
libblkid1:amd64\
libboost-iostreams1.54.0:amd64\
libbsd0:amd64\
libbz2-1.0:amd64\
libbz2-dev:amd64\
libc-bin\
libc-dev-bin\
libc6:amd64\
libc6-dev:amd64\
libcairo-gobject2:amd64\
libcairo-script-interpreter2:amd64\
libcairo2:amd64\
libcairo2-dev\
libcap-ng0\
libcap2:amd64\
libcap2-bin\
libcdt5\
libcgmanager0:amd64\
libcgraph6\
libck-connector0:amd64\
libclass-accessor-perl\
libcloog-isl4:amd64\
libcomerr2:amd64\
libcroco3:amd64\
libcryptsetup4\
libcups2:amd64\
libcupsfilters1:amd64\
libcupsimage2:amd64\
libcurl3:amd64\
libcurl3-gnutls:amd64\
libcurl4-openssl-dev:amd64\
libcwidget3\
libdatrie1:amd64\
libdb5.3:amd64\
libdbus-1-3:amd64\
libdbus-glib-1-2:amd64\
libdebconfclient0:amd64\
libdevmapper1.02.1:amd64\
libdjvulibre-dev:amd64\
libdjvulibre-text\
libdjvulibre21:amd64\
libdns100\
libdpkg-perl\
libdrm2:amd64\
libdumbnet1\
libedit2:amd64\
libelf1:amd64\
libelfg0:amd64\
libept1.4.12:amd64\
liberror-perl\
libestr0\
libev4\
libevent-2.0-5:amd64\
libexif-dev\
libexif12:amd64\
libexpat1:amd64\
libexpat1-dev:amd64\
libfakeroot:amd64\
libffi6:amd64\
libfftw3-double3:amd64\
libfile-fcntllock-perl\
libfontconfig1:amd64\
libfontconfig1-dev\
libfreetype6:amd64\
libfreetype6-dev\
libfribidi0:amd64\
libfuse2:amd64\
libgc1c2:amd64\
libgcc-4.8-dev:amd64\
libgcc1:amd64\
libgck-1-0:amd64\
libgcr-3-common\
libgcr-base-3-1:amd64\
libgcrypt11:amd64\
libgcrypt11-dev\
libgd3:amd64\
libgdbm3:amd64\
libgdk-pixbuf2.0-0:amd64\
libgdk-pixbuf2.0-common\
libgdk-pixbuf2.0-dev\
libgeoip1:amd64\
libgettextpo-dev:amd64\
libgettextpo0:amd64\
libgirepository-1.0-1\
libglib2.0-0:amd64\
libglib2.0-bin\
libglib2.0-data\
libglib2.0-dev\
libgmp10:amd64\
libgnutls-dev\
libgnutls-openssl27:amd64\
libgnutls26:amd64\
libgnutlsxx27:amd64\
libgomp1:amd64\
libgpg-error-dev\
libgpg-error0:amd64\
libgpm2:amd64\
libgraphite2-3:amd64\
libgraphviz-dev\
libgs9\
libgs9-common\
libgssapi-krb5-2:amd64\
libgssapi3-heimdal:amd64\
libgssrpc4:amd64\
libgvc6\
libgvpr2\
libharfbuzz0b:amd64\
libhcrypto4-heimdal:amd64\
libheimbase1-heimdal:amd64\
libheimntlm0-heimdal:amd64\
libhx509-5-heimdal:amd64\
libice-dev:amd64\
libice6:amd64\
libicu52:amd64\
libidn11:amd64\
libidn11-dev\
libijs-0.35\
libilmbase-dev\
libilmbase6:amd64\
libio-string-perl\
libisc95\
libisccc90\
libisccfg90\
libisl10:amd64\
libitm1:amd64\
libjasper-dev\
libjasper1:amd64\
libjbig-dev:amd64\
libjbig0:amd64\
libjbig2dec0\
libjpeg-dev:amd64\
libjpeg-turbo8:amd64\
libjpeg-turbo8-dev:amd64\
libjpeg8:amd64\
libjpeg8-dev:amd64\
libjs-jquery\
libjson-c2:amd64\
libjson0:amd64\
libk5crypto3:amd64\
libkadm5clnt-mit9:amd64\
libkadm5srv-mit9:amd64\
libkdb5-7:amd64\
libkeyutils1:amd64\
libklibc\
libkmod2:amd64\
libkrb5-26-heimdal:amd64\
libkrb5-3:amd64\
libkrb5-dev\
libkrb5support0:amd64\
liblcms2-2:amd64\
liblcms2-dev:amd64\
libldap-2.4-2:amd64\
libldap2-dev:amd64\
liblocale-gettext-perl\
liblockfile-bin\
liblockfile1:amd64\
liblog-message-simple-perl\
liblqr-1-0:amd64\
liblqr-1-0-dev\
libltdl-dev:amd64\
libltdl7:amd64\
liblwres90\
liblzma-dev:amd64\
liblzma5:amd64\
liblzo2-2:amd64\
libmagic1:amd64\
libmagickcore-dev\
libmagickcore5:amd64\
libmagickcore5-extra:amd64\
libmagickwand-dev\
libmagickwand5:amd64\
libmail-sendmail-perl\
libmodule-pluggable-perl\
libmount1:amd64\
libmpc3:amd64\
libmpdec2:amd64\
libmpfr4:amd64\
libmysqlclient-dev\
libmysqlclient18:amd64\
libncurses5:amd64\
libncursesw5:amd64\
libnetpbm10\
libnewt0.52:amd64\
libnfnetlink0:amd64\
libnih-dbus1:amd64\
libnih1:amd64\
libnuma1:amd64\
libopenexr-dev\
libopenexr6:amd64\
libp11-kit-dev\
libp11-kit0:amd64\
libpam-cap:amd64\
libpam-modules:amd64\
libpam-modules-bin\
libpam-runtime\
libpam-systemd:amd64\
libpam0g:amd64\
libpango-1.0-0:amd64\
libpangocairo-1.0-0:amd64\
libpangoft2-1.0-0:amd64\
libpaper-utils\
libpaper1:amd64\
libparse-debianchangelog-perl\
libparted0debian1:amd64\
libpathplan4\
libpcap0.8:amd64\
libpci3:amd64\
libpcre3:amd64\
libpcre3-dev:amd64\
libpcrecpp0:amd64\
libpipeline1:amd64\
libpixman-1-0:amd64\
libpixman-1-dev\
libplymouth2:amd64\
libpng12-0:amd64\
libpng12-dev\
libpod-latex-perl\
libpolkit-agent-1-0:amd64\
libpolkit-backend-1-0:amd64\
libpolkit-gobject-1-0:amd64\
libpopt0:amd64\
libpq-dev\
libpq5\
libprocps3:amd64\
libpthread-stubs0-dev:amd64\
libpython-stdlib:amd64\
libpython2.7:amd64\
libpython2.7-minimal:amd64\
libpython2.7-stdlib:amd64\
libpython3-stdlib:amd64\
libpython3.4-minimal:amd64\
libpython3.4-stdlib:amd64\
libquadmath0:amd64\
libreadline6:amd64\
libroken18-heimdal:amd64\
librsvg2-2:amd64\
librsvg2-common:amd64\
librsvg2-dev\
librtmp-dev\
librtmp0:amd64\
libruby1.9.1\
libsasl2-2:amd64\
libsasl2-modules:amd64\
libsasl2-modules-db:amd64\
libsctp-dev\
libsctp1:amd64\
libselinux1:amd64\
libsemanage-common\
libsemanage1:amd64\
libsepol1:amd64\
libsigc++-2.0-0c2a:amd64\
libsigsegv2:amd64\
libslang2:amd64\
libsm-dev:amd64\
libsm6:amd64\
libsqlite3-0:amd64\
libsqlite3-dev:amd64\
libss2:amd64\
libssl-dev:amd64\
libssl-doc\
libssl1.0.0:amd64\
libstdc++-4.8-dev:amd64\
libstdc++6:amd64\
libsub-name-perl\
libsys-hostname-long-perl\
libsystemd-daemon0:amd64\
libsystemd-login0:amd64\
libtasn1-6:amd64\
libtasn1-6-dev\
libterm-ui-perl\
libtext-charwidth-perl\
libtext-iconv-perl\
libtext-soundex-perl\
libtext-wrapi18n-perl\
libthai-data\
libthai0:amd64\
libtiff5:amd64\
libtiff5-dev:amd64\
libtiffxx5:amd64\
libtimedate-perl\
libtinfo5:amd64\
libtool\
libtsan0:amd64\
libudev1:amd64\
libunistring0:amd64\
libusb-0.1-4:amd64\
libusb-1.0-0:amd64\
libustr-1.0-1:amd64\
libuuid1:amd64\
libvpx1:amd64\
libwind0-heimdal:amd64\
libwmf-dev\
libwmf0.2-7:amd64\
libwrap0:amd64\
libx11-6:amd64\
libx11-data\
libx11-dev:amd64\
libx11-doc\
libxapian22\
libxau-dev:amd64\
libxau6:amd64\
libxcb-render0:amd64\
libxcb-render0-dev:amd64\
libxcb-shm0:amd64\
libxcb-shm0-dev:amd64\
libxcb1:amd64\
libxcb1-dev:amd64\
libxdmcp-dev:amd64\
libxdmcp6:amd64\
libxdot4\
libxext-dev:amd64\
libxext6:amd64\
libxml2:amd64\
libxml2-dev:amd64\
libxmuu1:amd64\
libxpm4:amd64\
libxrender-dev:amd64\
libxrender1:amd64\
libxt-dev:amd64\
libxt6:amd64\
libxtables10\
libyaml-0-2:amd64\
linux-headers-3.13.0-74\
linux-headers-3.13.0-74-generic\
linux-headers-generic\
linux-headers-virtual\
linux-image-3.13.0-74-generic\
linux-image-virtual\
linux-libc-dev:amd64\
linux-virtual\
lksctp-tools\
locales\
lockfile-progs\
login\
logrotate\
lsb-base\
lsb-release\
lshw\
lsof\
ltrace\
make\
makedev\
man-db\
manpages\
manpages-dev\
mawk\
mime-support\
mlocate\
module-init-tools\
mount\
mountall\
mtr-tiny\
multiarch-support\
mysql-common\
nano\
ncurses-base\
ncurses-bin\
ncurses-term\
net-tools\
netbase\
netcat-openbsd\
netpbm\
ntfs-3g\
ntpdate\
open-vm-tools\
openssh-client\
openssh-server\
openssh-sftp-server\
openssl\
os-prober\
overlayroot\
parted\
passwd\
patch\
pciutils\
perl\
perl-base\
perl-modules\
php5\
php5-cli\
php5-common\
php5-json\
php5-readline\
pkg-config\
plymouth\
plymouth-theme-ubuntu-text\
po-debconf\
policykit-1\
pollinate\
poppler-data\
popularity-contest\
powermgmt-base\
ppp\
pppconfig\
pppoeconf\
procps\
psmisc\
python\
python-apt\
python-apt-common\
python-chardet\
python-cheetah\
python-configobj\
python-debian\
python-gdbm\
python-json-pointer\
python-jsonpatch\
python-minimal\
python-oauth\
python-openssl\
python-pam\
python-pkg-resources\
python-prettytable\
python-pycurl\
python-requests\
python-serial\
python-six\
python-twisted-bin\
python-twisted-core\
python-twisted-names\
python-twisted-web\
python-urllib3\
python-xapian\
python-yaml\
python-zope.interface\
python2.7\
python2.7-minimal\
python3\
python3-apport\
python3-apt\
python3-commandnotfound\
python3-dbus\
python3-distupgrade\
python3-gdbm:amd64\
python3-gi\
python3-minimal\
python3-newt\
python3-problem-report\
python3-pycurl\
python3-software-properties\
python3-update-manager\
python3.4\
python3.4-minimal\
readline-common\
resolvconf\
rsync\
rsyslog\
ruby\
ruby-dev\
ruby-net-http-persistent\
ruby-passenger\
ruby-rack\
ruby-thor\
ruby1.9.1\
ruby1.9.1-dev\
rubygems-integration\
run-one\
screen\
sed\
sensible-utils\
sgml-base\
shared-mime-info\
software-properties-common\
ssh-import-id\
ssl-cert\
strace\
sudo\
systemd-services\
systemd-shim\
sysv-rc\
sysvinit-utils\
tar\
tasksel\
tasksel-data\
tcpd\
tcpdump\
telnet\
time\
tmux\
tzdata\
ubuntu-keyring\
ubuntu-minimal\
ubuntu-release-upgrader-core\
ubuntu-standard\
ucf\
udev\
ufw\
unattended-upgrades\
update-manager-core\
update-notifier-common\
upstart\
ureadahead\
usbutils\
util-linux\
uuid-dev\
uuid-runtime\
vim\
vim-common\
vim-runtime\
vim-tiny\
w3m\
wget\
whiptail\
x11-common\
x11proto-core-dev\
x11proto-input-dev\
x11proto-kb-dev\
x11proto-render-dev\
x11proto-xext-dev\
xauth\
xkb-data\
xml-core\
xorg-sgml-doctools\
xtrans-dev\
xz-utils\
zerofree\
zlib1g:amd64\
zlib1g-dev:amd64\
